2019-09-17 18:28:53,414 ERROR: Exception on / [GET] [in c:\users\seanc\documents\projectlambay\webdev\flask\donabateonline\venv\lib\site-packages\flask\app.py:1780]
Traceback (most recent call last):
  File "c:\users\seanc\documents\projectlambay\webdev\flask\donabateonline\venv\lib\site-packages\flask\app.py", line 2311, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\seanc\documents\projectlambay\webdev\flask\donabateonline\venv\lib\site-packages\flask\app.py", line 1834, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\seanc\documents\projectlambay\webdev\flask\donabateonline\venv\lib\site-packages\flask\app.py", line 1737, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\seanc\documents\projectlambay\webdev\flask\donabateonline\venv\lib\site-packages\flask\_compat.py", line 36, in reraise
    raise value
  File "c:\users\seanc\documents\projectlambay\webdev\flask\donabateonline\venv\lib\site-packages\flask\app.py", line 1832, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\seanc\documents\projectlambay\webdev\flask\donabateonline\venv\lib\site-packages\flask\app.py", line 1818, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\seanc\documents\projectlambay\webdev\flask\donabateonline\venv\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\seanc\Documents\projectlambay\webdev\Flask\donabateonline\app\routes.py", line 36, in index
    return render_template('index.html', title='Home', posts=posts)
  File "c:\users\seanc\documents\projectlambay\webdev\flask\donabateonline\venv\lib\site-packages\flask\templating.py", line 135, in render_template
    context, ctx.app)
  File "c:\users\seanc\documents\projectlambay\webdev\flask\donabateonline\venv\lib\site-packages\flask\templating.py", line 117, in _render
    rv = template.render(context)
  File "c:\users\seanc\documents\projectlambay\webdev\flask\donabateonline\venv\lib\site-packages\jinja2\asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "c:\users\seanc\documents\projectlambay\webdev\flask\donabateonline\venv\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "c:\users\seanc\documents\projectlambay\webdev\flask\donabateonline\venv\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\seanc\documents\projectlambay\webdev\flask\donabateonline\venv\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\seanc\Documents\projectlambay\webdev\Flask\donabateonline\app\templates\index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "C:\Users\seanc\Documents\projectlambay\webdev\Flask\donabateonline\app\templates\base.html", line 35, in top-level template code
    {% block content %}{% endblock %}
  File "C:\Users\seanc\Documents\projectlambay\webdev\Flask\donabateonline\app\templates\index.html", line 6, in block "content"
    {{ form.hidden_tag() }}
  File "c:\users\seanc\documents\projectlambay\webdev\flask\donabateonline\venv\lib\site-packages\jinja2\environment.py", line 430, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'form' is undefined
2019-09-17 18:50:09,691 INFO: Microblog statup [in C:\Users\seanc\Documents\projectlambay\webdev\Flask\donabateonline\app\__init__.py:49]
2019-09-17 18:50:25,055 ERROR: Exception on / [GET] [in c:\users\seanc\documents\projectlambay\webdev\flask\donabateonline\venv\lib\site-packages\flask\app.py:1780]
Traceback (most recent call last):
  File "c:\users\seanc\documents\projectlambay\webdev\flask\donabateonline\venv\lib\site-packages\flask\app.py", line 2311, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\seanc\documents\projectlambay\webdev\flask\donabateonline\venv\lib\site-packages\flask\app.py", line 1834, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\seanc\documents\projectlambay\webdev\flask\donabateonline\venv\lib\site-packages\flask\app.py", line 1737, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\seanc\documents\projectlambay\webdev\flask\donabateonline\venv\lib\site-packages\flask\_compat.py", line 36, in reraise
    raise value
  File "c:\users\seanc\documents\projectlambay\webdev\flask\donabateonline\venv\lib\site-packages\flask\app.py", line 1832, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\seanc\documents\projectlambay\webdev\flask\donabateonline\venv\lib\site-packages\flask\app.py", line 1818, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\seanc\documents\projectlambay\webdev\flask\donabateonline\venv\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\seanc\Documents\projectlambay\webdev\Flask\donabateonline\app\routes.py", line 36, in index
    return render_template('index.html', title='Home', posts=posts)
  File "c:\users\seanc\documents\projectlambay\webdev\flask\donabateonline\venv\lib\site-packages\flask\templating.py", line 135, in render_template
    context, ctx.app)
  File "c:\users\seanc\documents\projectlambay\webdev\flask\donabateonline\venv\lib\site-packages\flask\templating.py", line 117, in _render
    rv = template.render(context)
  File "c:\users\seanc\documents\projectlambay\webdev\flask\donabateonline\venv\lib\site-packages\jinja2\asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "c:\users\seanc\documents\projectlambay\webdev\flask\donabateonline\venv\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "c:\users\seanc\documents\projectlambay\webdev\flask\donabateonline\venv\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\seanc\documents\projectlambay\webdev\flask\donabateonline\venv\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\seanc\Documents\projectlambay\webdev\Flask\donabateonline\app\templates\index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "C:\Users\seanc\Documents\projectlambay\webdev\Flask\donabateonline\app\templates\base.html", line 35, in top-level template code
    {% block content %}{% endblock %}
  File "C:\Users\seanc\Documents\projectlambay\webdev\Flask\donabateonline\app\templates\index.html", line 6, in block "content"
    {{ form.hidden_tag() }}
  File "c:\users\seanc\documents\projectlambay\webdev\flask\donabateonline\venv\lib\site-packages\jinja2\environment.py", line 430, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'form' is undefined
